services:
  #####################
  # Olymipics dataset #
  #####################
  server-olympics:
    profiles:
      - olympics
    image: ghcr.io/zazukoians/qlever-server:latest
    build:
      context: ./docker/
      dockerfile: ./server.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7001:7001"
    env_file:
      - olympics.env
    volumes:
      - ./volumes/olympics/server:/data

  init-olympics:
    profiles:
      - olympics
    image: docker.io/library/busybox
    command:
      ["sh", "-c", "chown -R 65534:0 /data/server && chown -R 65534:0 /data/ui"]
    stop_grace_period: 0s
    restart: "no"
    volumes:
      - ./volumes/olympics/server:/data/server
      - ./volumes/olympics/ui:/data/ui

  ui-olympics:
    profiles:
      - olympics
    image: ghcr.io/zazukoians/qlever-ui:latest
    build:
      context: ./docker/
      dockerfile: ./ui.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7002:7002"
    depends_on:
      - server-olympics
    env_file:
      - olympics.env
    volumes:
      - ./volumes/olympics/ui:/app/db

  ###################
  # Local data file #
  ###################
  server-local:
    profiles:
      - local
    image: ghcr.io/zazukoians/qlever-server:latest
    build:
      context: ./docker/
      dockerfile: ./server.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7001:7001"
    environment:
      - FORCE_INDEXING=true
    env_file:
      - local.env
      # - empty.env # Use this instead of local.env to start with an empty database
    volumes:
      - ./volumes/local/server:/data
      - ./docker/server/data.nt:/data/data.nt:ro

  init-local:
    profiles:
      - local
    image: docker.io/library/busybox
    command:
      ["sh", "-c", "chown -R 65534:0 /data/server && chown -R 65534:0 /data/ui"]
    stop_grace_period: 0s
    restart: "no"
    volumes:
      - ./volumes/local/server:/data/server
      - ./volumes/local/ui:/data/ui

  ui-local:
    profiles:
      - local
    image: ghcr.io/zazukoians/qlever-ui:latest
    build:
      context: ./docker/
      dockerfile: ./ui.Dockerfile
    user: "65534:0"
    stop_grace_period: 0s
    ports:
      - "7002:7002"
    depends_on:
      - server-local
    env_file:
      - local.env
      # - empty.env # Use this instead of local.env to start with an empty database
    volumes:
      - ./volumes/local/ui:/app/db

  ######################
  # Petrimaps instance #
  ######################
  petrimaps-redirect-local:
    profiles:
      - local
    build:
      context: ./redirect/
      dockerfile: ./Dockerfile
    stop_grace_period: 0s
    environment:
      - PUBLIC_MAPS_URL=http://localhost:7004
      - PUBLIC_BACKEND_URL=http://localhost:7001
      - PRIVATE_BACKEND_URL=http://server-local:7001
    ports:
      - "7003:7003"

  petrimaps-redirect-olympics:
    profiles:
      - olympics
    build:
      context: ./redirect/
      dockerfile: ./Dockerfile
    stop_grace_period: 0s
    environment:
      - PUBLIC_MAPS_URL=http://localhost:7004
      - PUBLIC_BACKEND_URL=http://localhost:7001
      - PRIVATE_BACKEND_URL=http://server-olympics:7001
    ports:
      - "7003:7003"

  qlever-petrimaps:
    profiles:
      - local
      - olympics
    image: docker.io/adfreiburg/qlever-petrimaps:latest
    stop_grace_period: 0s
    restart: unless-stopped
    ports:
      - "7004:9090"
